function [H oc0] = groundH(alpha, beta, gamma, u0, v0, thetas, ts)
thetax = thetas(1);
thetay = thetas(2);
thetaz = thetas(3);

K = [...
    alpha gamma u0; ...
    0 beta v0; ...
    0 0 1];
Rx = [...
    1 0 0; ...
    0 cos(thetax) -sin(thetax); ...
    0 sin(thetax) cos(thetax)];
Ry = [... 
    cos(thetay) 0 sin(thetay); ...
    0 1 0; ...
    -sin(thetay) 0 cos(thetay)];
Rz = [...
    cos(thetaz) -sin(thetaz) 0; ...
    sin(thetaz) cos(thetaz) 0; ...
    0 0 1];
R = Rx*Ry*Rz;

oc0 = -R\ts; % optical center ground truth

H = K * [R(:,1) R(:,2) ts];
